#pragma once

// Wrapper header for application version.
// The actual APP_VERSION macro is generated into GitVersion.h by the Makefile,
// falling back to "dev" when that is not available.

#ifdef __has_include
#  if __has_include("GitVersion.h")
#    include "GitVersion.h"
#  endif  // __has_include("GitVersion.h")
#endif  // __has_include

#ifndef APP_VERSION
#define APP_VERSION "dev"  // NOSONAR(cpp:S5028) - Must remain macro, generated by CMake/Makefile build system
#endif  // APP_VERSION

// Centralized application display name for UI and window titles.
// Keep this in sync with app.manifest and documentation.
// NOLINTNEXTLINE(cppcoreguidelines-macro-usage) - Macro simplifies string literal reuse and concatenation in other macros; kept for compatibility with existing UI title definitions
#define APP_DISPLAY_NAME_STR "The FindHelper Experiment"  // NOSONAR(cpp:S5028) - Macro needed for compile-time string literal concatenation in HELP/METRICS title macros
#define HELP_WINDOW_TITLE_STR APP_DISPLAY_NAME_STR " – Help"
#define METRICS_WINDOW_TITLE_STR APP_DISPLAY_NAME_STR " Metrics"

// NOLINTNEXTLINE(readability-identifier-naming) - UPPER_SNAKE_CASE for app display name (sync with app.manifest/docs)
inline constexpr const char* APP_DISPLAY_NAME = APP_DISPLAY_NAME_STR;

