#pragma once

// Git-derived application version only. For static display name / window titles,
// include AppIdentity.h instead — it does not pull in GitVersion.h.

#ifdef __has_include
#  if __has_include("GitVersion.h")
#    include "GitVersion.h"
#  endif  // __has_include("GitVersion.h")
#endif  // __has_include

#ifndef APP_VERSION
#define APP_VERSION "dev"  // NOSONAR(cpp:S5028) - Must remain macro, generated by CMake/Makefile build system
#endif  // APP_VERSION
